version: "3.8"
services:
  backend:
    build:
      context: ../
      dockerfile: .devcontainer/backend
    image: backend_image
    stdin_open: true
    tty: true
    container_name: backend_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - type: volume
        source: backend_volume
        target: /home/developer/backend
  db:
    image: postgres
    container_name: db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bluemark

volumes:
  backend_volume: