version: "3.8"
services:
  bluemark:
    build:
      context: ../
      dockerfile: .devcontainer/bluemark
    image: bluemark_image
    stdin_open: true
    tty: true
    container_name: bluemark_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - type: volume
        source: bluemark_volume
        target: /home/developer/bluemark
  db:
    image: postgres
    container_name: db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bluemark

volumes:
  bluemark_volume: