version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    image: app_image
    container_name: app_container
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - "db"
    volumes:
      - type: volume
        source: app_volume
        target: /home/developer/app
    environment:
      BACKEND_PORT: 8080
      FRONTEND_PORT: 8888
  db:
    build:
      context: ../
      dockerfile: .devcontainer/db
    image: db_image
    container_name: db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bluemark

volumes:
  app_volume: